### ISSUE TITLE
[hcacc] Fails to change crypto type for hca files that loop

### ISSUE THREAD

**Issue by RagdollClash** [hozuki/libcgss#1]
For some reason, when converting looped hcas with hcacc, it doesn't change properly. It only changes a few bytes.

[Daytona USA's Sky High under Crypto Type #1](https://puu.sh/sgxHQ/78871b5abe.hca)
[That hca file under Crypto Type #0](https://puu.sh/sgxIP/73c3080e5d.hca)

**Comment by hozuki** [comment]
I'll look into it. Thanks for the feedback. :)

**Comment by hozuki** [comment]
OK I got it. I wrote a condition to prevent converting looped audio. At the time when I wrote that I wasn't sure if looping is connected with encryption.
And a tip for decoding looped audio: you can use _kawashima_'s "streaming" extension (`KsEnableExtension`, `KsPrepareExtensions`, `KsExtStreamingSeek`, `KsExtStreamingRead`, see [here](https://github.com/hozuki/foo_input_hca/blob/master/foo_input_hca/input_hca.cpp)). The "extension" is ugly and I'm thinking of refactoring the API. 😟
