### ISSUE TITLE
Compatibility issue when one Cue has multiple sub wav files

### ISSUE THREAD

**Issue by YueLengM** [hozuki/libcgss#11]
当一个 cue 对应多个 wav 文件时，文件命名会发生错位。一般来说一个 cue 是对应一个 wav 文件的，但我这里遇到了一种 ACB+AWB+XML 的打包方式，可能是通过 XML 里的信息来定位的。

![Snipaste_2020-04-13_13-29-38](https://user-images.githubusercontent.com/11801894/79094775-28673500-7d8b-11ea-8423-a9053de97bd1.png)
比如上图的 `CueID 92` 的 `prd_cv_0001_prf01` 对应 4 条音轨，但是只会将一个文件命名为 `prd_cv_0001_prf01` 下一个文件会被命名为 `CueID 93` 对应的文件名，导致 3 个文件的偏移。但只影响显示，不影响最终输出的音频。

本来是想通过自己写一个程序解决的，但是发现导出的 wav 文件数和 XML 中总音轨数不符。( #10 )

[cv_0001.zip](https://github.com/hozuki/libcgss/files/4468114/cv_0001.zip)
`-b 00000000 -a C59E7114`

**Comment by hozuki** [comment]
在 09617765faada36717aa037f443adb05686113dc 中通过添加waveform的列举方式做了修正。
