### ISSUE TITLE
Feature: Add prefix to Cue name

### ISSUE THREAD

**Issue by YueLengM** [hozuki/libcgss#12]
![Snipaste_2020-04-19_10-35-16](https://user-images.githubusercontent.com/11801894/79678015-8a131d80-8229-11ea-8027-272e5ac97c23.png)
之前我犯蠢了，说成了 174 个，但其实是 131 个，和 `"有名字的" cue` 数量一致。所以是给 131 个命了名的文件加前缀，剩下没命名的暂时就不管了。

**Comment by hozuki** [comment]
加了功能，但好像还是不能从根本上解决#11。应该有一种办法列出每个cue所包含的track（如XML文件里显示的那样）。

**Comment by YueLengM** [comment]
> 加了功能，但好像还是不能从根本上解决#11。应该有一种办法列出每个cue所包含的track（如XML文件里显示的那样）。

应该只能去解析 XML。那些 XML 是作为游戏资源文件出现的，也就是说 acb 和 awb 里都不包含额外的信息，所以额外信息只能从 XML 里提取。XML 结尾也有 CRI 的版权注释在里面，所以应该是官方的一种格式（acb + awb + XML），只是我们之前都没遇到过而已。

**Comment by hozuki** [comment]
这个我保持怀疑态度。在以前调试的时候（#4）见过 Atom 识别出一个cue，但是播放的时候是4条音轨，音量联动的。说明ACB里面保存着某种信息。

**Comment by hozuki** [comment]
这些条目是通过 `SequenceTable` 关联起来的。
试试[新的build](https://ci.appveyor.com/project/hozuki/libcgss/builds/32439387)：

```cmd
acb2hcas cv_0001.acb -b 00000000 -a C59E7114 -n -prependid -discovery:cue
```

**Comment by YueLengM** [comment]
大佬，真的太强了，我是完全搞不懂这种序列化文件。

**Comment by hozuki** [comment]
我不是大佬，只是对照文件结构猜测一下而已。
同时 #11 也应该解决了……
