### ISSUE TITLE
acb2wavs doesn't support looping?

### ISSUE THREAD

**Issue by Rohul1997** [hozuki/libcgss#8]
Hello
I don't think acb2wavs supports looping or am I doing something wrong?
A track from Dragalia Lost gets outputted with a length of 1:29 when its actually meant to be 3:25.
I've attached the acb and awb files that I tried with.
[raid.zip](https://github.com/hozuki/libcgss/files/3203696/raid.zip)

**Comment by hozuki** [comment]
acb2wavs does not support looping by default...

But is the time alright? I mean, the decoded time equals to overall time (with looped content only plays once).

**Comment by Rohul1997** [comment]
I believe the time is alright.

If not by default then how do I get it to loop? I've been using vgmstream for a lot of the tracks which are looped automatically but I've come across a couple tracks that just get exported as static noise. I've tried those tracks with acb2wavs and they get exported correctly but just not looped.

**Comment by RagdollClash** [comment]
Those tracks that are static noises don't have their subkeys baked into vgmstream yet: it should **only** be anything from and past the Lost Heroes event along with most sound effects/voice clips.

**Comment by Rohul1997** [comment]
Oh yes that's right. Also thanks I managed to get it to work with vgmstream by giving it the correct subkeys

**Comment by hozuki** [comment]
To enable looping you can modify the fields in `decoderConfig`: https://github.com/hozuki/libcgss/blob/56041aa0fa8ad371bc892636d917b9876b6dfcae/src/apps/acb2wavs/acb2wavs.cpp#L172

---

vgmstream is like a de facto standard... I start to think I should make a utility that generates companion .hcakey for vgmstream from acbs. Then it does not have to bake those keys in the code.

**Comment by Rohul1997** [comment]
Oh nice. Also that would actually be super useful if you could do that. Thanks for your help

**Comment by hozuki** [comment]
@Rohul1997 The [new release](https://github.com/hozuki/libcgss/releases/tag/v0.3.1) contains a utility to do that. But you still have to get the main key yourself.

**Comment by Rohul1997** [comment]
Ayy thanks a lot. I've just tried it and it kinda works how its meant to.
For some Dragalia Lost tracks `.bin` files get exported which are also `.hca` files that are normally separate vocal and instrumental tracks. The problem is using acb2hcas the `.bin` files that get exported inside the `external` folders are files filled with zeros in hex. Other than that the `.hca` and `.hcakey` files that get exported work fine with vgmstream.

**Comment by hozuki** [comment]
I guess you meant "`internal` folders".

Well, it may be another "linking" or "aliasing". And they *are* filled with zeroes, for unknown reasons. You can check out the internal AWB in `raid.acb`. (Search for "AFS2" in a hex editor.)

**Comment by Rohul1997** [comment]
No no I actually did mean the `external` folders because when using `acb2wavs` it exported to external and those `.bin` files if you rename them to `.wav` they play. So it should be the same with `acb2hcas` only difference is those `.bin` files should just be renamed to `.hca` but the problem is they are filled with zeroes and so contain nothing.

**Comment by Rohul1997** [comment]
Oh so when I use the `-n` parameter it gives 1 `.hca` file with the name and 2 `.bin` file inside the `external` folder. The `.hca` file is fine and has the correct content but the 2 `.bin` files are filled with zeroes.

When I don't use the `-n` parameter it gives 3 `.bin` files inside the `external` folder. All 3 are `.hca` files and do have the correct content inside.


The same file names + extensions are exported inside the `internal` folder but those are just couple kb files that don't have the actual content.

**Comment by hozuki** [comment]
It's weird, the name should not affect reading streams. Anyway this should be fixed in a [new release](https://github.com/hozuki/libcgss/releases/tag/v0.3.2).

**Comment by Rohul1997** [comment]
Thanks! Just tried and it works perfectly now. I guess I can close this now.
